# Generated by Django 5.0.3 on 2024-03-05 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innodom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='for_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='innodom.project'),
        ),
    ]
